### PR TITLE
add jhub/nbgitpuller to baseimage

### PR DESCRIPTION
**Pull request by jhamman**
cc @scottyhq

### CODE REVIEW

**Comment by scottyhq** [comment]
@jhamman - it looks like your branch isn't up-to-date with the latest master?

**Comment by jhamman** [comment]
Thanks @scottyhq - git is hard :wink:. Should be all good here now.

**Comment by jhamman** [comment]
This should fix the problem we're having in https://github.com/pangeo-data/pangeo-cloud-federation/pull/362

```
kubectl logs -n ocean-staging jupyter-0000-2d0001-2d7479-2d8439

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labhubapp.py", line 9, in <module>
    from jupyterhub.singleuser import SingleUserNotebookApp
ModuleNotFoundError: No module named 'jupyterhub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-labhub", line 7, in <module>
    from jupyterlab.labhubapp import main
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labhubapp.py", line 12, in <module>
    raise ImportError('You must have jupyterhub installed for this to work.')
ImportError: You must have jupyterhub installed for this to work.
```

**Comment by scottyhq** [comment]
That's a strange error. You should have already have jupyterhub from here https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml

it's definitely on the base-notebook image (launch from staging.nasa.pangeo.io or https://github.com/scottyhq/pangeo-binder-test/tree/pangeo-base )
`jupyterhub                1.0.0                    py37_0    conda-forge`

**Comment by scottyhq** [comment]
the logs on nasa-staging `kubectl logs -n nasa-staging jupyter-scottyhq` show a bunch of errors related to dask-labextension until you launch a kubernetes cluster and open up some bokeh tabs (I think b/c the de-async branch) just keep polling for the existence of the cluster and ignores the errors until it finds one...

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 94, in get
    return await self.http_get(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 303, in http_get
    return await self.proxy(port, proxied_path)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 199, in proxy
    response = await client.fetch(req, raise_error=False)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/iostream.py", line 1200, in connect
    self.socket.connect(address)
OSError: [Errno 99] Cannot assign requested address
SingleUserLabApp - ERROR - Uncaught exception GET /user/scottyhq/proxy/8787/statics/images/dask-logo.svg?1565285011093 (192.168.33.176)
HTTPServerRequest(protocol='https', host='staging.nasa.pangeo.io', method='GET', uri='/user/scottyhq/proxy/8787/statics/images/dask-logo.svg?1565285011093', version='HTTP/1.1', remote_ip='192.168.33.176')
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/tcpclient.py", line 143, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 94, in get
    return await self.http_get(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 303, in http_get
    return await self.proxy(port, proxied_path)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 199, in proxy
    response = await client.fetch(req, raise_error=False)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/iostream.py", line 1200, in connect
    self.socket.connect(address)
OSError: [Errno 99] Cannot assign requested address
[I 2019-08-08 17:24:47.124 SingleUserLabApp handlers:259] Trying to establish websocket connection to ws://localhost:8787/individual-task-stream/ws?bokeh-protocol-version=1.0&bokeh-session-id=2MxxsG1GjO5v799HtOE3Q6iwR5BSwOHO2bPiKZLwdn09
[I 2019-08-08 17:24:47.128 SingleUserLabApp handlers:265] Websocket connection established to ws://localhost:8787/individual-task-stream/ws?bokeh-protocol-version=1.0&bokeh-session-id=2MxxsG1GjO5v799HtOE3Q6iwR5BSwOHO2bPiKZLwdn09
```

**Comment by jhamman** [comment]
I've merged this so we can test things out on pangeo-cloud-federation/staging.

**Comment by jhamman** [comment]
@scottyhq - I don't think these "errors" are related. This looks like mostly known behavior of the lab-extension (pre-async).

**Comment by scottyhq** [comment]
true. and i realized nasa-staging isn't bringing in the 2019-08-08 image, but a previous one, so feel free to bump again. i think if you remove `@jupyterlab/hub-extension` we will no longer have `File --> Hub Control Panel` menu item

**Comment by jhamman** [comment]
The labhub extension was deprecated with jupyterlab 1.0: https://github.com/jupyterhub/jupyterlab-hub.

**Comment by scottyhq** [comment]
@jhamman - ok. good to know. I still don't understand why you weren't ending up with jupyterhub b/c that should come from repo2docker and was there in my binder test. but if it's working let's just stick with it.

**Pull request merged**
