### PR TITLE
more verification checks

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by jhamman** [comment]
@rabernat - ideas as to why the ocean image is failing in the verify step?

**Comment by rabernat** [comment]
It's an intermittent conda error:
```
CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/pyviz/label/earthsim/noarch/datashader-0.6.9a1-py_0.tar.bz2>
```

This happened a bunch yesterday too. Then I got around it by restarting the build, and I'm trying the same here.

If we go with the new hefty pangeo-notebook image, I can drop pangeo-ocean. The size was not too big.

**Comment by jhamman** [comment]
The rebuild core dumped in the ocean tests. I guess this is what we want the tests to catch...

**Comment by jhamman** [comment]
merging since #24 will remove the failing tests.

**Pull request merged**
