### PR TITLE
Fix onbuild images to prevent resolving environment when launched with binder

### PR DESCRIPTION
**Pull request by scottyhq**
seems like this line got removed by accident in PR related to implementing the `start` sidecar file.

hopefully fixes https://github.com/pangeo-data/pangeo-stacks/issues/134 

@rabernat, @yuvipanda, @tjcrone

### CODE REVIEW

**Comment by yuvipanda** [comment]
I like it!

**Comment by yuvipanda** [comment]
Unless this was causing it to be confused about 'start' and thus making the tests fail, in which case I don't like it.

We shall watch the test and see, I guess!

**Comment by yuvipanda** [comment]
@scottyhq I can't seem to find it - is there a test for 'start'? If this doesn't break 'start', it's good to go I think.

**Comment by scottyhq** [comment]
I don't think we have a test for `start` :( ... if you have a recommendation I can add something. Maybe just confirming an environment variable gets set? with `docker run` ?  https://github.com/pangeo-data/pangeo-stacks/tree/master/pangeo-notebook/binder/tests

**Pull request merged**
