### PR TITLE
added esip env

### PR DESCRIPTION
**Pull request by rsignell-usgs**
@scottyhq suggested I add the ESIP environment here so we can point to on the profile list on deployments like: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/icesat2/config/common.yaml#L87

Please check, as it's my first time trying this and likely got some minor thing wrong.

### CODE REVIEW

**Comment by scottyhq** [comment]
Looks fine to me @rsignell-usgs . Are you able to merge PRs in this repo ?

**Comment by rsignell-usgs** [comment]
@scottyhq yup!  Okay, we'll give it a shot!

**Comment by jhamman** [comment]
@rsignell-usgs - fine that this was merged. I'm curious why you are building off of the base-notebook as opposed to the pangeo-notebook. There seems to be almost a 1:1 mapping. Thoughts?

**Comment by rsignell-usgs** [comment]
@jhamman, um, I guess just because that's the way I was building the [ESIP container  at cloud-federation](https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/esip/image/binder).    Is there an efficiency gain to build off pangeo-notebook, or just a bit cleaner?

**Pull request merged**
