### PR TITLE
silence dask logs

### PR DESCRIPTION
**Pull request by scottyhq**
@jhamman @TomAugspurger 

anything else to add ? maybe idle_timeout? https://github.com/pangeo-data/pangeo/issues/712#issuecomment-528179934

### CODE REVIEW

**Comment by TomAugspurger** [comment]
For context, we're seeing that

```python
cluster = KubeCluster(n_workers=2)
```

prints out

```
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://192.168.110.92:37081
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Register tcp://192.168.104.201:35159
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.104.201:35159
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://192.168.113.158:33417
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.113.158:33417
distributed.core - INFO - Starting established connection
```

to stderr, which notebook / jupyterlab formats like a warning. Similar for connecting a Client.

**Comment by TomAugspurger** [comment]
cc @jacobtomlinson and @mrocklin, just for visibility since distributed and dask-kubernetes users may run into this more frequently now (if my guess about this being related to the SpecCluster refactor is correct).

**Comment by jacobtomlinson** [comment]
Yeah this is likely related to the rewrite. By default we create a `dask.distributed.Scheduler` object and I think that is where these warnings are generated.

This is similar to what other `SpecCluster` implementations do so this may pop up in other places.

**Comment by jhamman** [comment]
+1 on adding `idle_timeout`!

**Pull request merged**
