### PR TITLE
bump versions

### PR DESCRIPTION
**Pull request by jhamman**
I'm prepping for the cmip6 hack next week. This is the first round of version bumps. 

cc @andersy005 @rabernat

### CODE REVIEW

**Comment by rabernat** [comment]
Here is the full list of stuff that got added to ocean on top of the pangeo-notebook image

https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ocean/image/binder/environment.yml
```yaml
name: pangeo
channels:
  - conda-forge
dependencies:
  - altair
  - basemap
  - cc-plugin-ncei
  - ciso
  - cmocean
  - compliance-checker
  - ctd
  - descartes
  - erddapy
  - folium
  - fsspec
  - geolinks
  - gridgeo
  - ioos-tools
  - palettable
  - pocean-core
  - podaacpy
  - pyoos
  - retrying
  - seaborn
  - sympy
  - unyt
  - utide
  - vega
  - vega_datasets
  - xhistogram
  - xlrd
  - xmitgcm>=0.4.1
  - datashader>=0.7  # temporary (force update from base image)
  - geoviews>=1.6.3  # temporary (force update from base image)
  - python-wget
  - prefect
  - pip:
    - graphviz
```

Maybe we want to bring some of these into the main notebook image?

**Comment by rabernat** [comment]
A few more ideas:

- https://github.com/bradyrx/climpred
- https://github.com/CNES/pangeo-pytide
- https://github.com/CNES/pangeo-pyinterp

**Comment by jhamman** [comment]
> Here is the full list of stuff that got added to ocean on top of the pangeo-notebook image

Can you distill this list for me. What should I add here?

**Comment by jhamman** [comment]
More updates on Monday. This will allow us to test the initial env change over the weekend.

**Pull request merged**
