### PR TITLE
matrix

### PR DESCRIPTION
**Pull request by ocefpaf**
Not sure if we can run these in parallel but @rsignell-usgs was running in some timeout issues early today (already solved by Travis-CI) and I was wondering if this is possible and/or if it would help. If this does not make sense feel free to close it.

### CODE REVIEW

**Comment by jhamman** [comment]
We need to run the `base-notebook` job first. I know job dependencies are possible in other CI systems but I'm not sure about Travis. @ocefpaf - do you have thoughts here?

**Comment by ocefpaf** [comment]
> @ocefpaf - do you have thoughts here?

Both issue you mentioned are worth pursing IMO. However, Travis-CI usually increases the time of OSS builds when requested so, if no one has the time to make the change I recommend asking them first. (I believe that @rsignell-usgs already did and already got the extra time BTW.)

I would also look into Azure. It is quite fast and offers 6 hours for OSS projects.

PS: just for fun I modified the config here to see if we can get somewhere with the job matrix.

**Comment by scottyhq** [comment]
Thanks @ocefpaf !  @jhamman - thoughts on merging this for now? I also noticed we probably don't need to build "onbuild" images other than base-notebook and pangeo-notebook (https://hub.docker.com/r/pangeo/pangeo-esip-onbuild/tags). 

If going away with travis, it's also worth considering GitHub Actions - https://github.com/scottyhq/repo2docker-githubci

**Comment by rsignell-usgs** [comment]
Wow, github actions does look pretty cool!  This [nice blog post](https://www.markphelps.me/2019/09/migrating-from-travis-to-github-actions/)  about migrating from travis to github actions also mentions  [github secrets support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#creating-and-using-secrets-encrypted-variables) which I didn't know about either!

**Comment by jhamman** [comment]
I would be a big fan of someone working on github actions here. If either of you (@rsignell-usgs or @ocefpaf) want to take a swing at it, I'm happy to set you up with the necessary permissions.

**Comment by ocefpaf** [comment]
I can take a look at this over the weekend and see if it is a low hanging fruit. I'll let you know next Monday.

**Comment by ocefpaf** [comment]
Closing this b/c the effort seems to be on #108

**Pull request closed without merging**
