### PR TITLE
Bump Python, jlab, and tornado versions.

### PR DESCRIPTION
**Pull request by TomAugspurger**
- python 3.6 -> 3.7
- jupyterlab -> 1.0.0
- tornado 5.1.1 -> 6.0.3

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Are we OK with the 3.6 -> 3.7 change? Or should I just focus on jupyterlab for now?

**Comment by scottyhq** [comment]
This is great, thanks @TomAugspurger! Are the Tornado>6 issues fixed? Seemed like there were lots of issues with JupyterHub and dask previously. We tried bumping to Python 3.7 a while back and there was some issue building the images... Maybe with repo2docker, but I think it should be fine now.

**Comment by TomAugspurger** [comment]
Distributed fixed the tornado 6 issues in https://github.com/dask/distributed/pull/2570. Notebook fixed them in https://github.com/jupyter/notebook/issues/4439. So we should be OK, but who knows :)

I'm not sure when to deploy updates to binder.pangeo.io and prod.pangeo.io. I'll be offline tomorrow and most of Friday for the holiday.

**Comment by scottyhq** [comment]
going to go ahead and merge this to experiment w/ jupyterlab 1.0. i'll just note that things currently seem to work well with Docker image 2019.07.01 if things break.

**Pull request merged**
