### PR TITLE
Update pangeo-notebook environment

### PR DESCRIPTION
**Pull request by rabernat**
This is a huge-ish update to the pangeo-notebook environment.

I think it would be wise for us to have a docker container that is pretty full of most of the package we generally want in most environments.

Questions I have about this are:
- will there by weird gdal / rasterio library issues? (hopefully now covered by tests)
- how big will this image be?
- should we pin *every* package or just the most important ones? what is the best practice?

### CODE REVIEW

**Comment by rabernat** [comment]
Surprisingly all the environment tests works, meaning we have working rasterio, geoviews, etc.

The dask test failed like this
```
    def test_check_dask_version(client):
        print(client)
        versions = client.get_versions(check=True)
>       assert len(versions) == 4
E       assert 3 == 4
E         -3
E         +4

binder/tests/test_dask_env.py:13: AssertionError
----------------------------- Captured stdout call -----------------------------
<Client: scheduler='tcp://127.0.0.1:43816' processes=4 cores=4>
```

@jhamman - you wrote this test - any idea what's going on?

**Comment by jhamman** [comment]
I would bet the test is wrong. I think it should read `len(versions == 3)`.

**Comment by rabernat** [comment]
According to the distributed [code](http://distributed.dask.org/en/latest/_modules/distributed/client.html#Client.get_versions), the output of the `get_versions` function looks like this
```python
result = {'scheduler': scheduler, 'workers': workers, 'client': client}
```

What are you trying to test with this test?

**Comment by jhamman** [comment]
This test was originally intended as a demo. I don't think I put that much though into it. I'd be okay removing the assert line or changing the value to 3.

**Comment by rabernat** [comment]
Ok this passed. I'm going to merge and push a new image. Let's see how big it is! 😬

**Pull request merged**
